# Make sure to change the action name here (must be unique).
# Update the rest as needed.
name: 'datalad-zenodo-upload'
description: 'Action to upload a datalad repo to Zenodo, including all .git so that once unzip, it can be used with datalad. Dataset can be checked-out recursively with an optional recursion limit.'
branding:
  icon: 'upload'
  color: 'blue'
inputs:
  zenodo_token:
    description: The Zenodo token used to authenticated with Zenodo.
    required: true
  recursion_limit:
    description: 'recursion depth of the dataset that we want to release'
    default: 0
  archive_format:
    description: 'format of the archive we want to push, following shutil.make_archive syntax'
    default: "gztar"
  sandbox:
    description: 'submit to zenodo sandbox'
    required: 'false'
    default: 'false'
outputs:
  zenodo_doi:
    description: 'generated DOI'
  zenodo_url:
    description: 'URL to zenodo record'
  archive_url:
    description: 'URL to archive'
runs:
  using: 'docker'
  image: docker://ghcr.io/bids-flux/datalad-zenodo-upload:main
  env:
    ZENODO_API_TOKEN: ${{ inputs.zenodo_token }}
    ZENODO_SANDBOX_API_TOKEN: ${{ inputs.zenodo_token }}
    GIT_USERNAME: Github action
    GIT_EMAIL: action@github.com
  args:
    - --recursion-limit
    - ${{ inputs.recursion_limit }}
    - --archive-format
    - ${{ inputs.archive_format }}
    - ${{ inputs.sandbox=='true' && '--sandbox' || '--no-sandbox' }}
