# Make sure to change the action name here (must be unique).
# Update the rest as needed.
name: 'datalad-zenodo-upload'
description: 'BRIEF DESCRIPTION OF YOUR ACTION'
branding: # Look at documentation for branding options/requirements. These are my favorites.
  icon: 'upload'
  color: 'blue'
inputs:
  recursion_limit:
    description: 'recursion depth of the dataset that we want to release'
    type: int
    default: 0
  zenodo_creds:
    description: 'zenodo credentials'
    required: true

outputs:
  zenodo_doi:
    description: 'generated DOI'
  zenodo_url:
    description: 'URL to zenodo record'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.input-one }}
    - ${{ inputs.input-two }}
