# Make sure to change the action name here (must be unique).
# Update the rest as needed.
name: 'datalad-zenodo-upload'
description: 'BRIEF DESCRIPTION OF YOUR ACTION'
branding: # Look at documentation for branding options/requirements. These are my favorites.
  icon: 'upload'
  color: 'blue'
inputs:
  zenodo_token:
    description: The Zenodo token used to authenticated with Zenodo.
    required: true
  recursion_limit:
    description: 'recursion depth of the dataset that we want to release'
    type: int
    default: 0
  archive_format:
    description: 'format of the archive we want to push, following shutil.make_archive syntax'
    type: str
    default: "gztar"
  sandbox:
    description: 'submit to zenodo sandbox'
    type: bool
    default: false
outputs:
  zenodo_doi:
    description: 'generated DOI'
  zenodo_url:
    description: 'URL to zenodo record'
  archive_url:
    description: 'URL to archive'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    ZENODO_API_TOKEN: ${{ inputs.zenodo_token }}
    ZENODO_SANDBOX_API_TOKEN: ${{ inputs.zenodo_token }}
  args:
    - "--recursion-limit"
    - "${{ inputs.recursion_limit }}"
    - "--archive-format"
    - "${{ inputs.archive_format }}"
    - "${{ inputs.sandbox && '--sandbox' }}"
